In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import os

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [3]:
os.getcwd()

'C:\\Users\\pmgho'

In [4]:
os.chdir('C:\\Users\\pmgho\\Downloads\\prajwal_main_data\\')

In [5]:
os.getcwd()

'C:\\Users\\pmgho\\Downloads\\prajwal_main_data'

In [6]:
df = pd.read_csv('train (1).csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df = pd.read_csv('train (1).csv',usecols=['Age','Fare','Survived'])
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Age       714 non-null    float64
 2   Fare      891 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 21.0 KB

In [9]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [10]:
df.isnull().mean()

Survived    0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [11]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [13]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [14]:
X

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [15]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 2)
(179, 2)
(712,)
(179,)

In [18]:
X_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

### Without this technique my accuracy is......?ðŸ¤”

In [19]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)  # Ye puri values maine mean se fill kr di hain......

In [20]:
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [21]:
X_test_trf

array([[ 42.        ,  26.2875    ],
       [ 21.        ,   8.05      ],
       [ 24.        ,  65.        ],
       [ 28.        ,  56.4958    ],
       [ 17.        ,   7.925     ],
       [ 30.        ,   7.8958    ],
       [ 80.        ,  30.        ],
       [ 25.        ,   7.25      ],
       [ 50.        , 133.65      ],
       [ 25.        ,  26.        ],
       [ 35.        ,  26.        ],
       [ 35.        ,  90.        ],
       [ 55.        ,  16.        ],
       [ 29.78590426,  56.4958    ],
       [ 29.78590426,  56.4958    ],
       [ 19.        ,   7.8542    ],
       [ 29.78590426,  15.2458    ],
       [ 49.        ,   0.        ],
       [ 18.        ,  14.4542    ],
       [ 65.        ,   7.75      ],
       [ 18.        , 108.9       ],
       [ 29.78590426,  22.3583    ],
       [ 16.        ,  18.        ],
       [ 21.        ,   9.825     ],
       [ 19.        ,   6.75      ],
       [  1.        ,  11.1333    ],
       [ 50.        ,  10.5       ],
       [ 37.        ,  53.1       ],
       [ 28.        ,   9.5       ],
       [ 54.        ,  14.        ],
       [ 20.        ,   7.925     ],
       [ 36.        ,   0.        ],
       [  6.        ,  31.275     ],
       [ 29.78590426,  50.        ],
       [ 40.        ,  31.        ],
       [ 26.        ,  16.1       ],
       [ 30.        ,  93.5       ],
       [  1.        ,  46.9       ],
       [ 29.78590426,   7.8958    ],
       [ 35.        ,  10.5       ],
       [ 38.        ,   7.05      ],
       [ 44.        ,  16.1       ],
       [ 22.        ,   7.75      ],
       [ 18.        ,   6.4958    ],
       [ 21.        ,   8.4333    ],
       [ 29.78590426, 227.525     ],
       [ 21.        ,  77.9583    ],
       [ 29.78590426,   8.6625    ],
       [ 22.        ,   7.225     ],
       [ 27.        ,  10.5       ],
       [ 29.78590426,   8.05      ],
       [ 51.        ,  26.55      ],
       [ 28.        ,  33.        ],
       [ 47.        ,  38.5       ],
       [ 32.        ,  10.5       ],
       [ 48.        ,  52.        ],
       [ 10.        ,  24.15      ],
       [ 21.        ,   8.6625    ],
       [ 51.        ,   7.0542    ],
       [ 32.        ,   7.925     ],
       [ 42.        ,  13.        ],
       [  2.        ,  26.        ],
       [ 35.        ,   8.05      ],
       [ 29.78590426,   7.25      ],
       [  2.        ,  10.4625    ],
       [ 33.        ,   9.5       ],
       [ 48.        ,  25.9292    ],
       [ 55.        ,  30.5       ],
       [  1.        ,  39.6875    ],
       [ 17.        ,   7.0542    ],
       [ 24.        ,  15.85      ],
       [ 74.        ,   7.775     ],
       [ 29.78590426,  24.15      ],
       [ 28.        ,   7.7958    ],
       [ 26.        ,   7.8542    ],
       [  1.        ,  39.        ],
       [ 18.        ,   8.05      ],
       [  3.        ,  26.        ],
       [ 48.        ,  39.6       ],
       [ 32.        ,  56.4958    ],
       [ 19.        ,  91.0792    ],
       [ 29.78590426,  42.4       ],
       [ 70.        ,  10.5       ],
       [ 34.        ,  26.        ],
       [ 39.        , 110.8833    ],
       [ 17.        ,  10.5       ],
       [ 38.        ,   8.6625    ],
       [ 29.78590426,   7.8958    ],
       [ 30.        ,  21.        ],
       [ 28.        ,  13.        ],
       [ 29.78590426,   7.725     ],
       [ 19.        ,   8.1583    ],
       [ 29.        ,   7.75      ],
       [ 29.78590426,   7.8958    ],
       [ 44.        ,   7.925     ],
       [ 22.        ,  41.5792    ],
       [ 21.        ,  34.375     ],
       [ 41.        ,  19.5       ],
       [ 29.78590426,   7.225     ],
       [ 25.        ,  55.4417    ],
       [  0.92      , 151.55      ],
       [ 44.        ,  26.        ],
       [ 19.        ,  26.        ],
       [ 30.        ,  56.9292    ],
       [ 20.        ,   9.5       ],
       [  5.        ,  12.475     ],
       [  4.        ,  39.        ],
       [ 29.78590426,  16.1       ],
       [ 38.        ,   0.        ],
       [ 28.        ,  22.525     ],
       [ 29.78590426,  30.        ],
       [ 29.        ,   7.775     ],
       [ 49.        ,  89.1042    ],
       [ 19.        ,  14.5       ],
       [ 18.        , 262.375     ],
       [ 31.        ,  26.25      ],
       [ 27.        ,   7.7958    ],
       [ 36.        , 120.        ],
       [  8.        ,  36.75      ],
       [  2.        ,  21.075     ],
       [ 63.        ,  77.9583    ],
       [ 31.        ,   7.75      ],
       [ 29.78590426,   0.        ],
       [ 25.        ,  13.        ],
       [ 20.5       ,   7.25      ],
       [ 29.78590426,   7.8958    ],
       [ 64.        , 263.        ],
       [ 19.        ,  26.        ],
       [ 18.        ,   7.775     ],
       [ 29.78590426,   0.        ],
       [ 29.78590426,   7.8958    ],
       [ 11.        ,  18.7875    ],
       [ 15.        ,  14.4542    ],
       [ 22.        ,  55.        ],
       [ 50.        ,  13.        ],
       [ 28.        ,  14.4       ],
       [ 39.        ,  13.        ],
       [ 29.78590426,   8.05      ],
       [ 39.        ,   7.925     ],
       [ 24.        ,  16.1       ],
       [ 23.        ,   7.925     ],
       [ 17.        ,  57.        ],
       [ 44.        ,  26.        ],
       [ 23.        ,  13.7917    ],
       [ 29.78590426,  26.55      ],
       [ 52.        ,  78.2667    ],
       [ 24.5       ,   8.05      ],
       [ 55.5       ,   8.05      ],
       [ 18.        ,   7.7958    ],
       [ 18.        ,  13.        ],
       [ 45.        ,  83.475     ],
       [ 31.        ,  18.        ],
       [ 30.5       ,   8.05      ],
       [ 42.        ,   8.4042    ],
       [ 29.78590426,   7.75      ],
       [ 36.        ,   7.4958    ],
       [ 34.        ,  26.55      ],
       [ 54.        ,  78.2667    ],
       [ 15.        ,   8.0292    ],
       [ 25.        ,   7.775     ],
       [ 26.        ,  30.        ],
       [ 29.78590426,   8.1125    ],
       [ 19.        ,   8.05      ],
       [ 29.        ,   7.8958    ],
       [ 19.        ,  30.        ],
       [ 33.        ,  90.        ],
       [ 36.        ,  24.15      ],
       [ 29.78590426,   7.775     ],
       [ 35.        , 512.3292    ],
       [ 22.        ,   7.25      ],
       [ 29.78590426,  16.1       ],
       [ 18.        ,   7.4958    ],
       [ 28.        ,  26.        ],
       [ 22.        ,   7.25      ],
       [ 24.        ,   8.05      ],
       [ 22.        ,   9.        ],
       [ 29.78590426,  69.55      ],
       [ 26.        ,   7.8958    ],
       [ 29.        ,  10.4625    ]])

In [22]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

In [23]:
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

MissingIndicator()

In [24]:
mi.features_

array([0], dtype=int64)

In [25]:
X_train_missing = mi.transform(X_train)

X_train_missing

In [27]:
X_test_missing = mi.transform(X_test)

In [28]:
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

In [29]:
X_train['Age_NA'] = X_train_missing

In [29]:
X_train

      Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [32]:
X_test['Age_NA'] = X_test_missing

In [33]:
X_train

      Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [48]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.fit_transform(X_test)

In [49]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_pred)

1.0

In [50]:
si =SimpleImputer(add_indicator=True)

In [51]:
X_train = si.fit_transform(X_train)

In [52]:
X_test = si.transform(X_test)

In [57]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression() 
clf.fit(X_train_trf2,y_train)
y_pred = clf.predict(X_test_trf2)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.6312849162011173